<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Laporan Prestasi</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; color: #1E2328; padding: 20px; }
        .header { text-align: center; border-bottom: 3px solid #F5B301; padding-bottom: 12px; margin-bottom: 20px; }
        .header h1 { font-size: 18px; }
        .header h2 { font-size: 14px; color: #C28A00; font-weight: normal; }
        .header p { font-size: 9px; color: #6B7280; margin-top: 4px; }
        table { width: 100%; border-collapse: collapse; }
        thead { background: #F5B301; }
        thead th { color: #1E2328; padding: 8px 6px; text-align: left; font-size: 9px; text-transform: uppercase; }
        tbody td { padding: 6px; border-bottom: 1px solid #E5E7EB; font-size: 9px; }
        tbody tr:nth-child(even) { background: #F9FAFB; }
        .footer { position: fixed; bottom: 0; text-align: center; font-size: 8px; color: #6B7280; padding-top: 8px; border-top: 1px solid #E5E7EB; width: 100%; }
    </style>
</head>
<body>
    <div class="header">
        <h1>KESENIAN GIRI ADIWARNA</h1>
        <h2>SMK NEGERI 1 BANJAR</h2>
        <p>Laporan Prestasi · Dicetak {{ now()->translatedFormat('d F Y, H:i') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 4%;">No</th>
                <th style="width: 25%;">Nama Lomba</th>
                <th style="width: 12%;">Kategori</th>
                <th style="width: 10%;">Tingkat</th>
                <th style="width: 10%;">Peringkat</th>
                <th style="width: 7%;">Tahun</th>
                <th style="width: 15%;">Penyelenggara</th>
                <th style="width: 17%;">Peserta</th>
            </tr>
        </thead>
        <tbody>
            @foreach($achievements as $i => $p)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ $p->nama_lomba }}</td>
                    <td>{{ $p->kategori ?? '-' }}</td>
                    <td>{{ $p->tingkat->shortLabel() }}</td>
                    <td>{{ $p->peringkat ?? '-' }}</td>
                    <td>{{ $p->tahun }}</td>
                    <td>{{ $p->penyelenggara ?? '-' }}</td>
                    <td>{{ $p->peserta->map(fn($ps) => $ps->user->nama_lengkap ?? '-')->implode(', ') ?: '-' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Total: {{ $achievements->count() }} prestasi · Generated by Giri Adiwarna Information System
    </div>
</body>
</html>