<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Laporan Kas</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; color: #1E2328; padding: 20px; }
        .header { text-align: center; border-bottom: 3px solid #F5B301; padding-bottom: 12px; margin-bottom: 20px; }
        .header h1 { font-size: 18px; }
        .header h2 { font-size: 14px; color: #C28A00; font-weight: normal; }
        .header p { font-size: 9px; color: #6B7280; margin-top: 4px; }
        .summary { background: #FFFBEB; border-left: 4px solid #F5B301; padding: 10px 15px; margin-bottom: 15px; }
        .summary-row { display: flex; justify-content: space-between; }
        .summary-row strong { color: #C28A00; }
        table { width: 100%; border-collapse: collapse; }
        thead { background: #F5B301; }
        thead th { color: #1E2328; padding: 8px 6px; text-align: left; font-size: 9px; text-transform: uppercase; }
        tbody td { padding: 6px; border-bottom: 1px solid #E5E7EB; font-size: 9px; }
        tbody tr:nth-child(even) { background: #F9FAFB; }
        .footer { position: fixed; bottom: 0; text-align: center; font-size: 8px; color: #6B7280; padding-top: 8px; border-top: 1px solid #E5E7EB; width: 100%; }
    </style>
</head>
<body>
    <div class="header">
        <h1>KESENIAN GIRI ADIWARNA</h1>
        <h2>SMK NEGERI 1 BANJAR</h2>
        <p>Laporan Kas · Dicetak {{ now()->translatedFormat('d F Y, H:i') }}</p>
    </div>

    <div class="summary">
        <div class="summary-row">
            <span>Total Pembayaran: <strong>{{ $payments->count() }}</strong></span>
            <span>Total Kas Lunas: <strong>Rp {{ number_format($total, 0, ',', '.') }}</strong></span>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 4%;">No</th>
                <th style="width: 20%;">Nama</th>
                <th style="width: 10%;">Periode</th>
                <th style="width: 15%;">Kategori</th>
                <th style="width: 12%;">Nominal</th>
                <th style="width: 10%;">Status</th>
                <th style="width: 12%;">Tgl Bayar</th>
                <th style="width: 17%;">Dicatat</th>
            </tr>
        </thead>
        <tbody>
            @foreach($payments as $i => $p)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ $p->user->nama_lengkap ?? '-' }}</td>
                    <td>{{ $p->periode_bulan }}</td>
                    <td>{{ $p->kategori->nama ?? '-' }}</td>
                    <td>Rp {{ number_format($p->nominal, 0, ',', '.') }}</td>
                    <td>{{ $p->status->label() }}</td>
                    <td>{{ $p->tanggal_bayar?->format('d/m/Y') ?? '-' }}</td>
                    <td>{{ $p->pencatat->nama_lengkap ?? '-' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Giri Adiwarna Information System
    </div>
</body>
</html>