<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Laporan Anggota</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; color: #1E2328; padding: 20px; }
        .header { text-align: center; border-bottom: 3px solid #F5B301; padding-bottom: 12px; margin-bottom: 20px; }
        .header h1 { font-size: 18px; color: #1E2328; margin-bottom: 4px; }
        .header h2 { font-size: 14px; color: #C28A00; font-weight: normal; }
        .header p { font-size: 9px; color: #6B7280; margin-top: 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        thead { background: #F5B301; }
        thead th { color: #1E2328; padding: 8px 6px; text-align: left; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; }
        tbody td { padding: 6px; border-bottom: 1px solid #E5E7EB; font-size: 9px; }
        tbody tr:nth-child(even) { background: #F9FAFB; }
        .footer { position: fixed; bottom: 0; left: 0; right: 0; text-align: center; font-size: 8px; color: #6B7280; padding-top: 8px; border-top: 1px solid #E5E7EB; }
    </style>
</head>
<body>
    <div class="header">
        <h1>KESENIAN GIRI ADIWARNA</h1>
        <h2>SMK NEGERI 1 BANJAR</h2>
        <p>Laporan Data Anggota · Dicetak {{ now()->translatedFormat('d F Y, H:i') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 4%;">No</th>
                <th style="width: 20%;">Nama Lengkap</th>
                <th style="width: 10%;">NIS</th>
                <th style="width: 15%;">Email</th>
                <th style="width: 8%;">Kelas</th>
                <th style="width: 10%;">Cabang</th>
                <th style="width: 12%;">Role</th>
                <th style="width: 10%;">Status</th>
                <th style="width: 11%;">No. HP</th>
            </tr>
        </thead>
        <tbody>
            @foreach($members as $i => $m)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ $m->nama_lengkap }}</td>
                    <td>{{ $m->nis ?? '-' }}</td>
                    <td>{{ $m->email }}</td>
                    <td>{{ $m->kelas ?? '-' }}</td>
                    <td>{{ $m->cabang?->shortLabel() ?? '-' }}</td>
                    <td>{{ $m->role->label() }}</td>
                    <td>{{ $m->status_anggota->label() }}</td>
                    <td>{{ $m->phone ?? '-' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Total: {{ $members->count() }} anggota · Generated by Giri Adiwarna Information System
    </div>
</body>
</html>