CREATE TYPE "role_user" AS ENUM (
  'anggota',
  'pdd',
  'bendahara',
  'sekretaris',
  'ketua',
  'wakil_ketua',
  'pembina'
);

CREATE TYPE "status_anggota" AS ENUM (
  'aktif',
  'alumni',
  'nonaktif'
);

CREATE TYPE "jenis_kegiatan" AS ENUM (
  'latihan',
  'pentas',
  'lomba',
  'rapat'
);

CREATE TYPE "status_absensi" AS ENUM (
  'hadir',
  'izin',
  'sakit',
  'alpa'
);

CREATE TYPE "status_kas" AS ENUM (
  'lunas',
  'belum_lunas'
);

CREATE TYPE "tipe_media" AS ENUM (
  'foto',
  'video'
);

CREATE TYPE "tingkat_prestasi" AS ENUM (
  'sekolah',
  'kabupaten',
  'provinsi',
  'nasional'
);

CREATE TYPE "target_pengumuman" AS ENUM (
  'semua',
  'anggota',
  'pengurus'
);

CREATE TABLE "users" (
  "id_user" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nis" varchar(20) UNIQUE,
  "nama_lengkap" varchar(100) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "role" role_user NOT NULL,
  "kelas" varchar(20),
  "jurusan" varchar(50),
  "angkatan" varchar(10),
  "status_anggota" status_anggota DEFAULT 'aktif',
  "photo" varchar(255),
  "phone" varchar(15),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "periode" (
  "id_periode" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_periode" varchar(20) NOT NULL,
  "tahun_mulai" int NOT NULL,
  "tahun_selesai" int NOT NULL,
  "is_active" boolean DEFAULT false
);

CREATE TABLE "jabatan" (
  "id_jabatan" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_jabatan" varchar(50) NOT NULL,
  "level" int
);

CREATE TABLE "kepengurusan" (
  "id_kepengurusan" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_user" int NOT NULL,
  "id_jabatan" int NOT NULL,
  "id_periode" int NOT NULL,
  "sk_number" varchar(50),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "jadwal_kegiatan" (
  "id_jadwal" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "judul" varchar(100) NOT NULL,
  "jenis" jenis_kegiatan NOT NULL,
  "tanggal" date NOT NULL,
  "jam_mulai" time,
  "jam_selesai" time,
  "lokasi" varchar(100),
  "qr_token" varchar(100) UNIQUE,
  "id_user_pembuat" int
);

CREATE TABLE "absensi" (
  "id_absensi" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_jadwal" int NOT NULL,
  "id_user" int NOT NULL,
  "status" status_absensi DEFAULT 'alpa',
  "waktu_absen" timestamp,
  "keterangan" text
);

CREATE TABLE "kas_kategori" (
  "id_kategori" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama" varchar(50) NOT NULL,
  "nominal" decimal(10,2) NOT NULL
);

CREATE TABLE "kas_pembayaran" (
  "id_pembayaran" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_user" int NOT NULL,
  "id_kategori" int NOT NULL,
  "periode_bulan" varchar(10),
  "nominal" decimal(10,2) NOT NULL,
  "status" status_kas DEFAULT 'belum_lunas',
  "tanggal_bayar" date,
  "bukti_pembayaran" varchar(255),
  "id_user_pencatat" int
);

CREATE TABLE "dokumentasi_album" (
  "id_album" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "judul" varchar(100) NOT NULL,
  "deskripsi" text,
  "cover_image" varchar(255),
  "id_jadwal" int,
  "id_user_uploader" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "dokumentasi_media" (
  "id_media" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_album" int NOT NULL,
  "tipe" tipe_media NOT NULL,
  "file_path" varchar(255) NOT NULL,
  "caption" varchar(150)
);

CREATE TABLE "prestasi" (
  "id_prestasi" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_lomba" varchar(100) NOT NULL,
  "kategori" varchar(50),
  "tingkat" tingkat_prestasi NOT NULL,
  "peringkat" varchar(20),
  "tahun" int NOT NULL,
  "foto" varchar(255),
  "deskripsi" text,
  "id_user_pencatat" int
);

CREATE TABLE "prestasi_peserta" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_prestasi" int NOT NULL,
  "id_user" int NOT NULL
);

CREATE TABLE "pengumuman" (
  "id_pengumuman" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "judul" varchar(150) NOT NULL,
  "isi" text NOT NULL,
  "target_role" target_pengumuman DEFAULT 'semua',
  "lampiran" varchar(255),
  "id_user_pembuat" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "audit_log" (
  "id_log" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_user" int,
  "action" varchar(50) NOT NULL,
  "module" varchar(50),
  "description" text,
  "ip_address" varchar(45),
  "created_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "periode"."nama_periode" IS 'contoh: 2025/2026';

COMMENT ON COLUMN "jabatan"."level" IS 'urutan struktur organisasi';

COMMENT ON COLUMN "jadwal_kegiatan"."qr_token" IS 'token untuk QR attendance';

COMMENT ON COLUMN "kas_kategori"."nama" IS 'kas bulanan, iuran event, dll';

COMMENT ON COLUMN "kas_pembayaran"."periode_bulan" IS 'contoh: 2026-01';

COMMENT ON COLUMN "audit_log"."action" IS 'create, update, delete, login';

COMMENT ON COLUMN "audit_log"."module" IS 'anggota, kas, absensi, dokumentasi, dll';

ALTER TABLE "kepengurusan" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id_user") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "kepengurusan" ADD FOREIGN KEY ("id_jabatan") REFERENCES "jabatan" ("id_jabatan") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "kepengurusan" ADD FOREIGN KEY ("id_periode") REFERENCES "periode" ("id_periode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "jadwal_kegiatan" ADD FOREIGN KEY ("id_user_pembuat") REFERENCES "users" ("id_user") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "absensi" ADD FOREIGN KEY ("id_jadwal") REFERENCES "jadwal_kegiatan" ("id_jadwal") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "absensi" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id_user") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "kas_pembayaran" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id_user") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "kas_pembayaran" ADD FOREIGN KEY ("id_kategori") REFERENCES "kas_kategori" ("id_kategori") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "kas_pembayaran" ADD FOREIGN KEY ("id_user_pencatat") REFERENCES "users" ("id_user") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dokumentasi_album" ADD FOREIGN KEY ("id_jadwal") REFERENCES "jadwal_kegiatan" ("id_jadwal") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dokumentasi_album" ADD FOREIGN KEY ("id_user_uploader") REFERENCES "users" ("id_user") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dokumentasi_media" ADD FOREIGN KEY ("id_album") REFERENCES "dokumentasi_album" ("id_album") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "prestasi" ADD FOREIGN KEY ("id_user_pencatat") REFERENCES "users" ("id_user") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "prestasi_peserta" ADD FOREIGN KEY ("id_prestasi") REFERENCES "prestasi" ("id_prestasi") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "prestasi_peserta" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id_user") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pengumuman" ADD FOREIGN KEY ("id_user_pembuat") REFERENCES "users" ("id_user") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_log" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id_user") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
