CREATE TYPE "user_role" AS ENUM (
  'anggota',
  'pdd',
  'bendahara',
  'sekretaris',
  'ketua',
  'wakil_ketua',
  'pembina',
  'admin'
);

CREATE TYPE "member_status" AS ENUM (
  'pending',
  'aktif',
  'nonaktif',
  'alumni',
  'lulus',
  'diblokir'
);

CREATE TYPE "attendance_status" AS ENUM (
  'hadir',
  'izin',
  'sakit',
  'alfa'
);

CREATE TYPE "announcement_audience" AS ENUM (
  'semua',
  'anggota',
  'pengurus'
);

CREATE TYPE "event_status" AS ENUM (
  'draft',
  'published',
  'archived'
);

CREATE TYPE "payment_status" AS ENUM (
  'paid',
  'pending',
  'late'
);

CREATE TYPE "media_type" AS ENUM (
  'photo',
  'video'
);

CREATE TYPE "notification_type" AS ENUM (
  'announcement',
  'cash_reminder',
  'attendance',
  'approval',
  'system'
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar NOT NULL,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE,
  "password" varchar NOT NULL,
  "phone" varchar,
  "photo_url" varchar,
  "nisn" varchar,
  "gender" varchar,
  "birth_date" date,
  "class_level" varchar,
  "major" varchar,
  "class_name" varchar,
  "role" user_role NOT NULL DEFAULT 'anggota',
  "status" member_status NOT NULL DEFAULT 'pending',
  "approved_by" integer,
  "approved_at" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "periods" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "start_year" integer NOT NULL,
  "end_year" integer NOT NULL,
  "status" varchar NOT NULL DEFAULT 'active',
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "positions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "category" varchar,
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "user_positions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "position_id" integer NOT NULL,
  "period_id" integer NOT NULL,
  "appointed_at" date,
  "ended_at" date,
  "is_current" boolean NOT NULL DEFAULT true,
  "note" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "announcements" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "slug" varchar UNIQUE,
  "content" text NOT NULL,
  "audience" announcement_audience NOT NULL DEFAULT 'semua',
  "image_url" varchar,
  "attachment_url" varchar,
  "published_by" integer NOT NULL,
  "status" event_status NOT NULL DEFAULT 'published',
  "published_at" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "events" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "slug" varchar UNIQUE,
  "description" text,
  "event_date" date,
  "location" varchar,
  "status" event_status NOT NULL DEFAULT 'draft',
  "created_by" integer NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "event_documentations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" integer NOT NULL,
  "uploaded_by" integer NOT NULL,
  "title" varchar,
  "caption" text,
  "file_url" varchar NOT NULL,
  "media_type" media_type NOT NULL,
  "sort_order" integer DEFAULT 0,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "event_participants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "role_in_event" varchar,
  "note" text,
  "created_at" timestamp
);

CREATE TABLE "attendance_sessions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "period_id" integer NOT NULL,
  "title" varchar NOT NULL,
  "meeting_date" date NOT NULL,
  "meeting_type" varchar,
  "qr_token" varchar,
  "qr_expires_at" timestamp,
  "created_by" integer NOT NULL,
  "is_locked" boolean NOT NULL DEFAULT false,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "attendance_records" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "status" attendance_status NOT NULL DEFAULT 'hadir',
  "note" text,
  "checked_in_via" varchar,
  "marked_by" integer,
  "marked_at" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "cash_dues" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "period_id" integer NOT NULL,
  "week_date" date NOT NULL,
  "amount" decimal(10,2) NOT NULL,
  "status" payment_status NOT NULL DEFAULT 'pending',
  "received_by" integer,
  "proof_url" varchar,
  "reminder_sent_at" timestamp,
  "note" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "achievements" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text,
  "achievement_date" date,
  "level" varchar,
  "image_url" varchar,
  "created_by" integer NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "audit_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "table_name" varchar NOT NULL,
  "record_id" integer NOT NULL,
  "action" varchar NOT NULL,
  "old_value" text,
  "new_value" text,
  "created_at" timestamp
);

CREATE TABLE "notifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "type" notification_type NOT NULL,
  "title" varchar NOT NULL,
  "message" text,
  "is_read" boolean NOT NULL DEFAULT false,
  "link_url" varchar,
  "created_at" timestamp
);

CREATE TABLE "site_settings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "site_name" varchar NOT NULL,
  "hero_title" varchar NOT NULL,
  "hero_subtitle" varchar,
  "about_text" text,
  "vision" text,
  "mission" text,
  "logo_url" varchar,
  "contact_email" varchar,
  "contact_person" varchar,
  "instagram_url" varchar,
  "youtube_url" varchar,
  "whatsapp_url" varchar,
  "updated_by" integer,
  "created_at" timestamp,
  "updated_at" timestamp
);

COMMENT ON COLUMN "users"."class_level" IS 'Contoh: 10 / 11 / 12';

COMMENT ON COLUMN "users"."major" IS 'Contoh: DKV, RPL, PM, BCF, TBS, MPLB, dll';

COMMENT ON COLUMN "users"."class_name" IS 'Contoh: 12 RPL 1';

COMMENT ON COLUMN "periods"."name" IS 'Contoh: 2026/2027';

COMMENT ON COLUMN "periods"."status" IS 'active / archived';

COMMENT ON COLUMN "positions"."name" IS 'Contoh: Ketua, Wakil Ketua, Sekretaris 1, Bendahara 1, PDD';

COMMENT ON COLUMN "positions"."category" IS 'inti / departemen / operasional';

COMMENT ON COLUMN "event_participants"."role_in_event" IS 'Contoh: penari, pemusik, among tamu, among tamu, among tamu';

COMMENT ON COLUMN "attendance_sessions"."meeting_type" IS 'latihan / rapat / tampil / umum';

COMMENT ON COLUMN "attendance_sessions"."qr_token" IS 'token unik untuk self check-in via QR';

COMMENT ON COLUMN "attendance_records"."checked_in_via" IS 'manual / qr';

COMMENT ON COLUMN "cash_dues"."amount" IS 'Contoh: 2000.00';

COMMENT ON COLUMN "achievements"."level" IS 'sekolah / kabupaten / provinsi / nasional';

COMMENT ON COLUMN "audit_logs"."user_id" IS 'siapa yang melakukan aksi';

COMMENT ON COLUMN "audit_logs"."action" IS 'create / update / delete';

ALTER TABLE "user_positions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_positions" ADD FOREIGN KEY ("position_id") REFERENCES "positions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_positions" ADD FOREIGN KEY ("period_id") REFERENCES "periods" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "announcements" ADD FOREIGN KEY ("published_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "events" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "event_documentations" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "event_documentations" ADD FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "event_participants" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "event_participants" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "attendance_sessions" ADD FOREIGN KEY ("period_id") REFERENCES "periods" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "attendance_sessions" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "attendance_records" ADD FOREIGN KEY ("session_id") REFERENCES "attendance_sessions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "attendance_records" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "attendance_records" ADD FOREIGN KEY ("marked_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cash_dues" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cash_dues" ADD FOREIGN KEY ("period_id") REFERENCES "periods" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cash_dues" ADD FOREIGN KEY ("received_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "achievements" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "site_settings" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "users" ADD FOREIGN KEY ("approved_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
